server:
  port: 9002
spring:
  application:
    name: tensquare-redislock
  redis:
    host: 129.204.172.72
    password: leige666
    database: 0
    lettuce:
      pool:
        max-wait: 5000
        max-active: 30
        max-idle: 30
        min-idle: 12
logging:
  level:
    root: debug
