server:
  port: 9300
spring:
  application:
    name: tensquare-gateway
  redis:
    host: 139.199.182.77
  cloud:
    gateway:
      discovery:
        locator:
          #开启服务注册与发现,如果开启将以服务名自动映射一个路由 localhost:9300/tensquare-base/label,当自定义路由的时候要设为false
          enabled: true
          #将注册中心的服务列表转为小写
          lower-case-service-id: true
      routes:
        - id: tensquare-base
          uri: lb://TENSQUARE-BASE
          predicates:
            - Path=/base/**
          filters:
           # - PrefixPath=/base
             - StripPrefix=1
             - name: Hystrix
                 args:
                   name: fallbackcmd
                   fallbackUri: forward:/fallback

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true